### ISSUE TITLE
 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by epenabella** [marhoy/nrk-download#16]
Could not download subtitles for program ... 'ascii' codec can't encode character u'\xe5' in position 131: ordinal not in range(128)

**Comment by marhoy** [comment]
For me to reproduce this, more info is needed:
- What are you trying to download (commandline)?
- What OS are you using?
- What Python version?

**Comment by epenabella** [comment]
2.7, windows 10,  https://tv.nrk.no/serie/vaar-tid-er-naa season 3

Regards,

Rick Penabella
+46723876999

-Sent from my mobile phone-

**Comment by marhoy** [comment]
Any particular episode?
I'm not able to reproduce the problem, have tried to download S03E01 using python-2.7.17 and 3.7.6 under OS X. So this seems to be related to your OS/installation.

Can you please try with python-3.7?
As Python-2 has reached end-of-life, support for python-2 will be dropped at some point.
Support for python 3.8 will be added in the next release.

**Comment by epenabella** [comment]
i tried just doing the whole season 3

i can try again tomorrow thanks so much for looking into it

Regards,

Rick Penabella
+46723876999

-Sent from my mobile phone-

**Comment by epenabella** [comment]
seems to be working now with python 3.7
