### ISSUE TITLE
Stuck at image download

### ISSUE THREAD

**Issue by viewsourc3** [marhoy/nrk-download#22]
**Describe the bug**
When I launch the download for an episode, it appears like it can't go past to the step "Downloading image for xxx"

**To Reproduce**
1. nrkdownload [insert link to season or episode] 
2. choose episode, or list of episodes.

**Expected behavior**
Nothing goes past beyond that point. Download should happen.

**Screenshots**
screenshot 1 - Verbose mode
![Screenshot 1](https://user-images.githubusercontent.com/76497381/121297498-aae97700-c8f2-11eb-8764-6103c0aa325c.png)

screenshot 2 - feedback when I quit (ctrl+c) 
![Screenshot 2](https://user-images.githubusercontent.com/76497381/121297508-ad4bd100-c8f2-11eb-9d93-8a29c7d09e24.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.7 (19H1217)
 - Nrkdownload Version 2.1.2, running under Darwin with Python 3.9.5

**Additional context**
Happy to provide more information if needed. 
I'm using a VPN to have access to nrk - as I live abroad. The episodes are accessible through firefox with no problem.

**Comment by marhoy** [comment]
I'm not able to reproduce (tested on Linux).
Could this be due to VPN or the Fastly problems?

**Comment by viewsourc3** [comment]
Possibly. I used to use another VPN to have access to NRK but had to change. Unfortunately, I cannot test with another VPN provider as of right now. 
For what it's worth, I can download no problem using youtube-dl. 

Let me know if I can help to provide any form of additional info if you want to have a closer look 
(sorry for delay of answer)
