### ISSUE TITLE
nrk-download + flexget for auto-download?

### ISSUE THREAD

**Issue by eivindml** [marhoy/nrk-download#4]
I currently use [`flexget`](https://flexget.com/) for automatic downloading of TV shows (which then is added to Plex ✌🏻). Do you/anyone know how to integrate nrk-download with flexget?

So that I can just add shows I want to watch in flexget's `config.yml` file, and it then executes nrkdownload app when new episodes are available?

As of now I can't see a way to do it, because it requires user input when executed. Would be great to add capabilities so that this is possible. 

Flexget has an [`exec` plugin](https://flexget.com/Plugins/exec) which will allow to run commands with parameters from flexget, and fork a new background process (so that lage downloads doesn't halt the flexget process).

**Comment by marhoy** [comment]
See the TODO section in the README regarding urls. Would that somehow help?
The idea then is to enable the script to run without user input, downloading e.g. all available episodes of a series (the ones that are already on disk, will be skipped)

**Comment by eivindml** [comment]
Yeah, great stuff. This kind of scheme seems perfect. Would be able to create something with flexget using this.

**Comment by Hellowlol** [comment]
I dont use flexget so i dont know what it returns but you can automate the input aslong as you know what to choose:

See https://github.com/Hellowlol/nrkdl/blob/master/tests/test_nrkdl.py#L118-L122 for a example

**Comment by marhoy** [comment]
The newly released version 0.9 has support for URL targets.
See the README on ow to update and how to use the new URL feature.

**Comment by eivindml** [comment]
Really cool. I'll see how to integrate this with flexget and post it here, in case someone else Google's it.
