### ISSUE TITLE
two-hour time limit per video

### ISSUE THREAD

**Issue by gabrielmass** [marhoy/nrk-download#6]
Tusen takk to marhoy for this fantastic tool!

When downloading long programs (for example, the second segment of "Hurtigruten minutt for minutt"), I find that the video stream stops at the two-hour time mark. This is not caused by your code, but appears to be an issue with the akamai streaming. 

My test: If I give the ffmpeg command manually in my Linux command window, and specify a start time of 1h59m, the stream still stops at 02h00m. 
% ffmpeg -loglevel 8 -stats -t 00:05:00 -ss 01:59:00 -i http://nordond4b-f.akamaihd.net/i/wo/open/f4/f4dc5a04a7ca5c406f5cc313d4bed5d0d87004a0/a5084291-fb0c-4a48-ba2d-6ea4f834bab7_,141,316,563,1266,2250,.mp4.csmil/master.m3u8 -c:v copy -c:a copy -bsf:a aac_adtstoasc "/mydisk/nrkdownload/Hurtigruten minutt for minutt/Season 01- 2011/Hurtigruten minutt for minutt - S01E02 - Bergen - Florø - 23.12.2011.m4v" 

Are you aware of any workaround for this behavior?  Again, thanks.

**Comment by marhoy** [comment]
Fixed in version 2.0.0
