### ISSUE TITLE
Programmes won't download

### ISSUE THREAD

**Issue by bottlehall** [marhoy/nrk-download#8]
If I try `nrkdownload -s skam`

I can list the series, choose one and get the list of programmes available. If I pick one, it takes about two minutes and then reports:

```
Enter a number or interval (e.g. 8 or 5-10). (q to quit): 33
Getting program details for your selection of 1 programs...
Ready to download 0 programs, with total duration 0:00:00
Downloading: 0.00s [00:00, ?s/s]
```

And returns to the command line prompt immediately.

**Comment by marhoy** [comment]
Hi,

Are you trying this from outside of Norway? Some content has geographical access restrictions.


Mvh,

Martin
-- 
Sendt fra iPhone

**Comment by bottlehall** [comment]
Hi,

Thanks for the quick reply. Yes, I am.

N

**Comment by bottlehall** [comment]
Hi

In the interests of solving the technical problem only, I had tried a few but the results are:

1. It completes without error, but no download file exists in the nrkdownload directory (-u method)
2. It errors with ERROR: Not able get details for skam: ('Connection aborted.', BadStatusLine("''",))

N
